theme: jekyll-theme-minimal
title: Robotics Lab URJC
description: First trial with githubpages


# Defaults
defaults:

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true